### ISSUE TITLE
449 - Serialize and Deserialize BST

### ISSUE THREAD

**Issue by All3yp** [Octet3290/Leetcode-Questions#49]
Hi, I want to solve [449 Leetcode problem](https://leetcode.com/problems/serialize-and-deserialize-bst/). It's about Serialize and Deserialize a binary search tree.
Please can you assign to me this issue? Thanks :)

**Comment by Octet3290** [comment]
Go ahead :)

> Hi, I want to solve [449 Leetcode problem](https://leetcode.com/problems/serialize-and-deserialize-bst/). It's about Serialize and Deserialize a binary search tree. Please can you assign to me this issue? Thanks :)

Go ahead

**Comment by Octet3290** [comment]
> Hi, I want to solve [449 Leetcode problem](https://leetcode.com/problems/serialize-and-deserialize-bst/). It's about Serialize and Deserialize a binary search tree. Please can you assign to me this issue? Thanks :)

Go ahead :)
